apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubepilot-demo
resources:
  - namespace.yaml
  - deployment.yaml
images:
  - name: docker.io/bwalia/kubepilot-demo-api
    newTag: latest
