package v1alpha1

import (
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/runtime/schema"
	"sigs.k8s.io/controller-runtime/pkg/scheme"
)

// GroupVersion is the API group/version for all KubePilot CRDs.
var GroupVersion = schema.GroupVersion{Group: "kubepilot.io", Version: "v1alpha1"}

// SchemeBuilder registers all KubePilot types into a scheme.
var (
	SchemeBuilder = &scheme.Builder{GroupVersion: GroupVersion}
	AddToScheme   = SchemeBuilder.AddToScheme
)

func init() {
	SchemeBuilder.Register(
		&KubePilotCluster{},
		&KubePilotClusterList{},
		&KubePilotJob{},
		&KubePilotJobList{},
		&KubePilotCRCode{},
		&KubePilotCRCodeList{},
	)
}

// Resource returns a GroupResource for the named resource type.
func Resource(resource string) schema.GroupResource {
	return GroupVersion.WithResource(resource).GroupResource()
}

// DeepCopyObject stubs — generated by controller-gen in production via 'make generate'.
// Placed here so the scaffold compiles without the generator running first.

func (in *KubePilotCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
func (in *KubePilotCluster) DeepCopy() *KubePilotCluster {
	if in == nil {
		return nil
	}
	out := new(KubePilotCluster)
	*out = *in
	return out
}

func (in *KubePilotClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
func (in *KubePilotClusterList) DeepCopy() *KubePilotClusterList {
	if in == nil {
		return nil
	}
	out := new(KubePilotClusterList)
	*out = *in
	return out
}

func (in *KubePilotJob) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
func (in *KubePilotJob) DeepCopy() *KubePilotJob {
	if in == nil {
		return nil
	}
	out := new(KubePilotJob)
	*out = *in
	return out
}

func (in *KubePilotJobList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
func (in *KubePilotJobList) DeepCopy() *KubePilotJobList {
	if in == nil {
		return nil
	}
	out := new(KubePilotJobList)
	*out = *in
	return out
}

func (in *KubePilotCRCode) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
func (in *KubePilotCRCode) DeepCopy() *KubePilotCRCode {
	if in == nil {
		return nil
	}
	out := new(KubePilotCRCode)
	*out = *in
	return out
}

func (in *KubePilotCRCodeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
func (in *KubePilotCRCodeList) DeepCopy() *KubePilotCRCodeList {
	if in == nil {
		return nil
	}
	out := new(KubePilotCRCodeList)
	*out = *in
	return out
}
