#!/usr/bin/env bash
# Install versioned Mac Studio runtime config into ~/.kubepilot.
# Called by Deploy → Mac Studio; safe to run manually.
#
#   bash deploy/macstudio/install-runtime.sh
#
# Never overwrites secrets.env. Migrates password out of a legacy start-server.sh
# into secrets.env on first install.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
SRC="$(cd "$(dirname "$0")" && pwd)"
DEST="${KUBEPILOT_HOME:-$HOME/.kubepilot}"
MODEL="$(grep -E '^KUBEPILOT_OLLAMA_MODEL=' "$SRC/kubepilot.env" | cut -d= -f2-)"
OLLAMA_URL="$(grep -E '^KUBEPILOT_OLLAMA_BASE_URL=' "$SRC/kubepilot.env" | cut -d= -f2-)"
# Allow CI / operator override without editing the committed env file.
MODEL="${KUBEPILOT_OLLAMA_MODEL:-$MODEL}"
OLLAMA_URL="${KUBEPILOT_OLLAMA_BASE_URL:-$OLLAMA_URL}"

mkdir -p "$DEST/bin" "$DEST/dashboard" "$DEST/logs" "$DEST/runbooks" "$DEST/state"

# ── Migrate secrets from legacy start-server.sh if needed ────────────────────
if [ ! -f "$DEST/secrets.env" ]; then
  pass=""
  kube=""
  if [ -f "$DEST/start-server.sh" ]; then
    pass="$(sed -n 's/.*KUBEPILOT_DASHBOARD_AUTH_PASSWORD="${KUBEPILOT_DASHBOARD_AUTH_PASSWORD:-\(.*\)}"/\1/p' "$DEST/start-server.sh" | head -1 || true)"
    kube="$(sed -n 's/.*KUBECONFIG="${KUBECONFIG:-\(.*\)}"/\1/p' "$DEST/start-server.sh" | head -1 || true)"
  fi
  PLIST="$HOME/Library/LaunchAgents/com.kubepilot.server.plist"
  if [ -z "$pass" ] && [ -f "$PLIST" ]; then
    pass="$(/usr/libexec/PlistBuddy -c 'Print :EnvironmentVariables:KUBEPILOT_DASHBOARD_AUTH_PASSWORD' "$PLIST" 2>/dev/null || true)"
  fi
  if [ -z "$kube" ] && [ -f "$PLIST" ]; then
    kube="$(/usr/libexec/PlistBuddy -c 'Print :EnvironmentVariables:KUBECONFIG' "$PLIST" 2>/dev/null || true)"
  fi
  {
    echo "# Generated by install-runtime.sh — local only, not in git."
    echo "KUBECONFIG=${kube:-$HOME/.kube/config}"
    echo "KUBEPILOT_DASHBOARD_AUTH_PASSWORD=${pass:-change-me}"
  } >"$DEST/secrets.env"
  chmod 600 "$DEST/secrets.env"
  echo "Created $DEST/secrets.env (chmod 600)"
fi

# ── Install versioned runtime files ──────────────────────────────────────────
install -m 644 "$SRC/kubepilot.env" "$DEST/kubepilot.env"
# Re-write model/url if overridden for this install.
if [ -n "${KUBEPILOT_OLLAMA_MODEL:-}" ] || [ -n "${KUBEPILOT_OLLAMA_BASE_URL:-}" ]; then
  tmp="$(mktemp)"
  sed \
    -e "s|^KUBEPILOT_OLLAMA_MODEL=.*|KUBEPILOT_OLLAMA_MODEL=${MODEL}|" \
    -e "s|^KUBEPILOT_OLLAMA_BASE_URL=.*|KUBEPILOT_OLLAMA_BASE_URL=${OLLAMA_URL}|" \
    "$SRC/kubepilot.env" >"$tmp"
  install -m 644 "$tmp" "$DEST/kubepilot.env"
  rm -f "$tmp"
fi
install -m 755 "$SRC/start-server.sh" "$DEST/start-server.sh"

# ── Keep launchd env in sync for the interactive model (no secrets here) ─────
PLIST="$HOME/Library/LaunchAgents/com.kubepilot.server.plist"
if [ -f "$PLIST" ]; then
  /usr/bin/plutil -replace EnvironmentVariables.KUBEPILOT_OLLAMA_MODEL -string "$MODEL" "$PLIST" 2>/dev/null \
    || /usr/bin/plutil -insert EnvironmentVariables.KUBEPILOT_OLLAMA_MODEL -string "$MODEL" "$PLIST"
  /usr/bin/plutil -replace EnvironmentVariables.KUBEPILOT_OLLAMA_BASE_URL -string "$OLLAMA_URL" "$PLIST" 2>/dev/null \
    || /usr/bin/plutil -insert EnvironmentVariables.KUBEPILOT_OLLAMA_BASE_URL -string "$OLLAMA_URL" "$PLIST"
fi

# ── Ensure Ollama has the pinned model; unload heavy thinkers ────────────────
export PATH="/opt/homebrew/bin:/usr/local/bin:$PATH"
if command -v ollama >/dev/null 2>&1; then
  echo "Ensuring Ollama model ${MODEL} is present…"
  # Dashboard pin is a local Modelfile derived from llama3.2:3b (4k ctx).
  if [ "$MODEL" = "llama3.2:3b-dash" ] && [ -f "$SRC/Modelfile.llama3.2-3b-dash" ]; then
    ollama pull llama3.2:3b || true
    ollama create llama3.2:3b-dash -f "$SRC/Modelfile.llama3.2-3b-dash" || true
  else
    ollama pull "$MODEL" || true
  fi
  for heavy in qwen3.8:latest qwen3.8-fast:latest qwen3-coder:30b qwen3:30b-a3b careerops:32k muse-glimmer:latest llama3.1:8b llama3.2:3b; do
    # Keep the pinned model loaded; stop everything else that steals GPU.
    [ "$heavy" = "$MODEL" ] && continue
    ollama stop "$heavy" 2>/dev/null || true
  done
  curl -s -m 180 "http://127.0.0.1:11434/api/generate" \
    -d "{\"model\":\"${MODEL}\",\"prompt\":\"ok\",\"stream\":false,\"keep_alive\":-1,\"options\":{\"num_predict\":1}}" \
    >/dev/null || true
  ollama ps || true
fi

echo "Mac Studio runtime installed → model=${MODEL} base_url=${OLLAMA_URL} dest=${DEST}"
echo "(repo root for reference: $ROOT)"
