apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubepilot.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubepilot.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.dashboardPort }}
      targetPort: dashboard
      protocol: TCP
      name: dashboard
    - port: {{ .Values.service.mcpPort }}
      targetPort: mcp
      protocol: TCP
      name: mcp
  selector:
    {{- include "kubepilot.selectorLabels" . | nindent 4 }}
